blank_issues_enabled: false
contact_links:
  - name: PynneX Documentation
    url: https://github.com/nexconnectio/pynnex/wiki/Contributing-to-PynneX
    about: Check our documentation before creating an issue
